# Generated by Django 3.0.5 on 2020-05-14 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200513_2215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_date',)},
        ),
        migrations.AlterModelOptions(
            name='commentreply',
            options={'ordering': ('created_date',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_date',)},
        ),
    ]
