# Generated by Django 3.0.5 on 2020-05-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200514_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('OM', 'only_me'), ('PU', 'public'), ('EF', 'except_friends'), ('OF', 'only_friends')], default='PU', max_length=2),
        ),
    ]
